#!/bin/sh
#
# Xcode Cloud: runs just before xcodebuild.
#
# Derives CFBundleVersion from the Xcode Cloud build number so build numbers
# are monotonic and App Store compatible, instead of being improvised from the
# local clock (§105).
#
# The value is written into Config/BuildNumber.xcconfig, which Config/Keezly.xcconfig
# includes optionally. Locally that file does not exist and the project keeps
# its committed default, so a developer build is unaffected.

set -eu

REPO="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
TARGET="$REPO/Config/BuildNumber.xcconfig"

echo "── Keezly: ci_pre_xcodebuild ──"

if [ -z "${CI_BUILD_NUMBER:-}" ]; then
    echo "CI_BUILD_NUMBER is not set — leaving the committed build number in place."
    echo "(This is expected outside Xcode Cloud.)"
    exit 0
fi

cat > "$TARGET" <<EOF
// Generated by ci_pre_xcodebuild.sh — do not edit, do not commit.
// Derived from the Xcode Cloud build number so CFBundleVersion is monotonic.
CURRENT_PROJECT_VERSION = ${CI_BUILD_NUMBER}
EOF

echo "CURRENT_PROJECT_VERSION = ${CI_BUILD_NUMBER}"
echo "written to $TARGET"
