#!/usr/bin/env bash
# Checks that the cues in the app are still the ones the generator makes.
#
#   ./scripts/sounds-check.sh
#
# Keezly's claim about its audio is that the source code *is* the provenance
# (§77): nothing sampled, nothing downloaded, no licence to wonder about. That
# claim is only worth anything if the shipped files can be reproduced from the
# source — otherwise "generated by `soundforge.py`" is a story about how the
# files were made once, which is not the same thing and is not checkable.
#
# So this regenerates them and compares. It is the same discipline as
# `icon-check.sh`, which fails if the committed icon PNGs stop matching
# `AppIconArtwork.swift`, and it exists for the same reason: a generated asset
# that has quietly been edited by hand is exactly the asset nobody remembers
# editing.
#
# Measured: the seven cues come out bit-for-bit identical across runs, so this
# compares hashes rather than tolerating drift. If a future change to the
# synthesis makes that untrue, the right answer is to regenerate and commit,
# not to loosen the comparison.
set -euo pipefail

cd "$(dirname "$0")/.." || exit 1
WORK="build/sounds-check"
SHIPPED="App/Keezly/Sounds"

rm -rf "$WORK"
python3 Tools/soundforge.py "$WORK" >/dev/null

failures=0
for wav in "$WORK"/*.wav; do
  name=$(basename "$wav" .wav)
  shipped="$SHIPPED/$name.caf"
  if [ ! -f "$shipped" ]; then
    echo "  ✘ $name.caf is not in the app"
    failures=$((failures + 1))
    continue
  fi
  # The shipped file is CAF, so the comparison is made on the decoded audio
  # rather than on the container: convert the freshly generated WAV the same
  # way the build does and compare those bytes.
  afconvert -f caff -d LEI16@44100 "$wav" "$WORK/$name.caf"
  if ! cmp -s "$WORK/$name.caf" "$shipped"; then
    echo "  ✘ $name.caf differs from what Tools/soundforge.py produces"
    failures=$((failures + 1))
  fi
done

echo
if [ "$failures" -eq 0 ]; then
  echo "All $(ls -1 "$SHIPPED"/*.caf | wc -l | tr -d ' ') cues regenerate exactly. The source is the provenance."
  exit 0
fi
echo "$failures cue(s) no longer match their source. Run ./scripts/sounds-build.sh."
exit 1
