#!/usr/bin/env python3
"""Keezly's sound set, synthesised from scratch.

Every cue in Keezly is generated by this file. Nothing is sampled, nothing is
downloaded, and nothing has a licence to wonder about: the provenance of the
audio is the source code that made it (§77).

The method is **modal synthesis** — the way a struck object actually sounds.
A small wooden piece set down on a board rings at a few inharmonic frequencies
that decay at different rates, with a brief broadband contact transient on top.
Summing decaying sinusoids at those frequencies is not an imitation of that; it
is a model of it, and it is why these read as wood rather than as beeps.

A playing card is the other half of the vocabulary: paper is almost entirely
broadband noise with a fast decay and very little below a kilohertz.

The design language is the board's: *tactile digital board game*. That rules
out, deliberately:

  - casino sounds — no coins, no chimes, no shuffle-riffle flourish
  - arcade beeps — nothing square-wave, nothing pitched to a game console
  - jingles — the two musical cues are a fifth and a triad, not a tune
  - anything triumphant enough to be embarrassing on the two hundredth win

Run through `scripts/sounds-build.sh`, which converts the output to CAF and
installs it. Requires nothing but the Python standard library.
"""

import array
import math
import os
import random
import sys
import wave

RATE = 44_100


# ---------------------------------------------------------------- primitives


def silence(seconds):
    return [0.0] * int(RATE * seconds)


def mix(into, signal, at=0.0, gain=1.0):
    """Adds `signal` into `into`, starting at `at` seconds."""
    start = int(RATE * at)
    needed = start + len(signal)
    if needed > len(into):
        into.extend([0.0] * (needed - len(into)))
    for index, value in enumerate(signal):
        into[start + index] += value * gain
    return into


def envelope(length, attack, decay, curve=1.0):
    """A fast attack and an exponential decay, in samples.

    The attack is what stops a click; the decay is what makes the thing sound
    struck rather than switched on.
    """
    out = []
    attack_samples = max(1, int(RATE * attack))
    for index in range(length):
        if index < attack_samples:
            level = index / attack_samples
        else:
            elapsed = (index - attack_samples) / RATE
            level = math.exp(-elapsed / decay)
        out.append(level ** curve)
    return out


def mode(frequency, seconds, decay, amplitude=1.0, attack=0.002, phase=0.0):
    """One resonant mode: a sinusoid that fades the way a struck body does."""
    length = int(RATE * seconds)
    shape = envelope(length, attack, decay)
    step = 2 * math.pi * frequency / RATE
    return [amplitude * shape[i] * math.sin(step * i + phase) for i in range(length)]


def noise(seconds, decay, low=0.0, high=1.0, amplitude=1.0, attack=0.001, seed=1):
    """A filtered burst of noise: the contact, the paper, the brush.

    `low` and `high` are one-pole coefficients rather than frequencies, which
    is all the shaping these very short sounds need — a steeper filter on a
    forty-millisecond burst is inaudible work.
    """
    generator = random.Random(seed)
    length = int(RATE * seconds)
    shape = envelope(length, attack, decay)

    out = []
    lowpassed = 0.0
    highpassed = 0.0
    previous = 0.0
    for index in range(length):
        sample = generator.uniform(-1.0, 1.0)
        # One-pole low-pass: keeps the body, loses the hiss.
        lowpassed += (sample - lowpassed) * high
        # One-pole high-pass: takes the rumble out.
        highpassed = low * (highpassed + lowpassed - previous)
        previous = lowpassed
        out.append(amplitude * shape[index] * highpassed)
    return out


def wood(frequency, seconds, decay, amplitude=1.0, seed=1):
    """A small wooden object being struck.

    Three modes in the ratios a short wooden bar actually rings at, the higher
    ones decaying faster — which is what makes a knock sound like wood and not
    like a bell — over a contact transient.
    """
    out = silence(seconds)
    mix(out, mode(frequency, seconds, decay, amplitude))
    mix(out, mode(frequency * 2.71, seconds, decay * 0.45, amplitude * 0.42))
    mix(out, mode(frequency * 5.36, seconds, decay * 0.22, amplitude * 0.18))
    mix(out, noise(min(seconds, 0.02), 0.006, low=0.88, high=0.55,
                   amplitude=amplitude * 0.55, seed=seed))
    return out


def mallet(frequency, seconds, decay, amplitude=1.0):
    """A tuned wooden bar — the voice the two musical cues are played on.

    A marimba bar is tuned so its second mode sits two octaves above the
    fundamental. That 1:4 ratio is the whole character: warm, hollow, and over
    quickly. Nothing here sustains, so neither cue can become a jingle.
    """
    out = silence(seconds)
    mix(out, mode(frequency, seconds, decay, amplitude))
    mix(out, mode(frequency * 4.0, seconds, decay * 0.35, amplitude * 0.30))
    mix(out, mode(frequency * 9.2, seconds, decay * 0.14, amplitude * 0.08))
    mix(out, noise(0.012, 0.004, low=0.9, high=0.6, amplitude=amplitude * 0.25, seed=7))
    return out


# -------------------------------------------------------------------- shaping


def normalise(signal, peak):
    """Scales to an exact peak, blocks any DC, and fades the tail.

    The DC blocker matters more than it sounds like it should: a low mode that
    does not complete a whole number of cycles inside a very short cue leaves
    a small offset, and an offset is a thump on every playback and headroom
    given away for nothing.
    """
    blocked = []
    previous_in = 0.0
    previous_out = 0.0
    for value in signal:
        # One-pole high-pass at about 20 Hz.
        previous_out = 0.9985 * (previous_out + value - previous_in)
        previous_in = value
        blocked.append(previous_out)

    highest = max((abs(value) for value in blocked), default=0.0)
    if highest == 0:
        return blocked
    gain = peak / highest
    out = [value * gain for value in blocked]

    fade = min(len(out), int(RATE * 0.006))
    for index in range(fade):
        out[len(out) - fade + index] *= 1 - index / fade
    return out


def write_wav(path, signal):
    frames = array.array("h")
    for value in signal:
        clamped = max(-1.0, min(1.0, value))
        frames.append(int(clamped * 32_767))
    with wave.open(path, "wb") as handle:
        handle.setnchannels(1)
        handle.setsampwidth(2)
        handle.setframerate(RATE)
        handle.writeframes(frames.tobytes())


# ---------------------------------------------------------------------- cues


def cue_select():
    """A card lifted off the others. The quietest thing in the set."""
    out = noise(0.035, 0.010, low=0.94, high=0.52, seed=11)
    return normalise(out, 0.14)


def cue_place():
    """A card set down on the board: paper first, then the panel under it."""
    out = silence(0.16)
    # The paper is the first thing you hear and the quieter of the two: a card
    # laid on a wooden board is mostly the board.
    mix(out, noise(0.05, 0.013, low=0.93, high=0.58, amplitude=0.45, seed=23))
    mix(out, wood(176, 0.14, 0.048, amplitude=1.0, seed=5), at=0.004)
    return normalise(out, 0.34)


def cue_swap():
    """Two pieces exchanged: one contact, then another, close together."""
    out = silence(0.26)
    mix(out, wood(212, 0.12, 0.040, amplitude=0.8, seed=31))
    mix(out, wood(188, 0.14, 0.046, amplitude=0.9, seed=37), at=0.085)
    return normalise(out, 0.32)


def cue_capture():
    """A piece knocked back. Harder, lower, and over quickly — a knock, not a
    crash: it happens to somebody several times a game."""
    out = silence(0.30)
    mix(out, wood(124, 0.26, 0.085, amplitude=1.0, seed=41))
    # A little low body, the sound of the board itself taking the blow.
    mix(out, mode(62, 0.18, 0.055, 0.34, attack=0.001))
    # Darker and quieter than the contact on a card. A heavier impact puts its
    # energy lower, and the first version measured *brighter* than the gentle
    # swap — which would have been the sound of a slap, not a knock.
    mix(out, noise(0.03, 0.009, low=0.80, high=0.30, amplitude=0.35, seed=43))
    return normalise(out, 0.58)


def cue_fold():
    """A dead hand swept aside. Paper only, no impact — nothing was placed."""
    out = noise(0.20, 0.055, low=0.90, high=0.34, seed=53)
    return normalise(out, 0.19)


def cue_home():
    """A piece safely in. Two notes a fifth apart, on the wooden bar.

    Calm on purpose. A player brings four pieces home every game and hears
    this every time; anything that celebrated would wear out by the second.
    """
    out = silence(0.75)
    mix(out, mallet(440.0, 0.55, 0.20, amplitude=0.9))          # A4
    mix(out, mallet(659.3, 0.60, 0.22, amplitude=0.75), at=0.13)  # E5
    mix(out, wood(190, 0.10, 0.035, amplitude=0.30, seed=59))
    return normalise(out, 0.42)


def cue_victory():
    """The match won. Four notes of a major triad, warm and short.

    A little over a second, on the same wooden bar as the home cue, so the end
    of a match sounds like the same instrument that has been playing all game.
    """
    out = silence(1.5)
    for index, (frequency, delay, amplitude) in enumerate([
        (587.3, 0.00, 0.85),   # D5
        (740.0, 0.115, 0.85),  # F#5
        (880.0, 0.230, 0.90),  # A5
        (1174.7, 0.345, 1.00),  # D6
    ]):
        length = 1.05 if index == 3 else 0.75
        decay = 0.42 if index == 3 else 0.26
        mix(out, mallet(frequency, length, decay, amplitude=amplitude), at=delay)
    # The lowest note underneath, quiet, so the chord has a floor.
    mix(out, mallet(293.7, 1.30, 0.50, amplitude=0.42), at=0.345)
    return normalise(out, 0.60)


CUES = {
    "select": cue_select,
    "place": cue_place,
    "swap": cue_swap,
    "capture": cue_capture,
    "fold": cue_fold,
    "home": cue_home,
    "victory": cue_victory,
}


def main():
    destination = sys.argv[1] if len(sys.argv) > 1 else "build/sounds"
    os.makedirs(destination, exist_ok=True)

    for name, make in sorted(CUES.items()):
        signal = make()
        path = os.path.join(destination, f"{name}.wav")
        write_wav(path, signal)
        peak = max(abs(value) for value in signal)
        print(f"  {name:9} {len(signal) / RATE:5.2f}s  peak {20 * math.log10(peak):6.1f} dBFS")


if __name__ == "__main__":
    main()
